# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    git clone https://github.com/andy-mishechkin/Azure-PipeLine-Test.git $(System.DefaultWorkingDirectory)/mProcessTools
    cd "$(System.DefaultWorkingDirectory)\mProcessTools"
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe" -target:library mProcessToolDll.cs
  displayName: 'Build mProcessTools dll'

- pwsh: |
    Write-Host "Build Status: [$env:AGENT_JOBSTATUS]"

- publish: $(System.DefaultWorkingDirectory)/mProcessTools/mProcessToolDll.dll

