# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    git clone https://github.com/andy-mishechkin/Azure-PipeLine-Test.git /mProcessTools
    cd /mProcessTools
    dir
    c:
    cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\"
    dir
      
  displayName: 'Build mProcessTools dll'

